#!/usr/bin/env python2
from websocket_server import WebsocketServer
from sensor_msgs.msg import NavSatFix, Imu
from tf.transformations import euler_from_quaternion
from point import Point
from sat_filter import SatFilter
from std_msgs.msg import Int8
from math import degrees
from gps_point import calc_goal
from visualization_msgs.msg import Marker
import rospy
import threading
import json
import actionlib
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal


class Controller:
    def __init__(self):
        self.server = WebsocketServer(9001)
        self.server.set_fn_message_received(self.socket_callback)
        t = threading.Thread(target=self.server.run_forever)
        t.daemon = True
        t.start()

        self.client = actionlib.SimpleActionClient('move_base', MoveBaseAction)
        self.client.wait_for_server()

        self.subscriber = rospy.Subscriber(
            '/piksi/navsatfix_rtk_fix',
            NavSatFix,
            self.callback_rtk,
        )
        self.subscriber = rospy.Subscriber(
            '/piksi/navsatfix_spp',
            NavSatFix,
            self.callback_spp,
        )
        self.subscriber = rospy.Subscriber(
            '/battery',
            Int8,
            self.callback_battery,
        )
        self.subscriber = rospy.Subscriber(
            '/imu/data',
            Imu,
            self.callback_imu,
        )
        self.gps_lat = float(rospy.get_param("gps_lat"))
        self.gps_lng = float(rospy.get_param("gps_lng"))

    def socket_callback(self, client, server, msg):
        data = json.loads(msg)
        lat = data["lat"]
        lng = data["lng"]
        x, y = calc_goal(self.gps_lat, self.gps_lng, lat, lng)
        rospy.logwarn("{} {}".format(x, y))
        
        goal = MoveBaseGoal()
        goal.target_pose.header.frame_id = "map"
        goal.target_pose.header.stamp = rospy.Time.now()
        goal.target_pose.pose.position.x = y
        goal.target_pose.pose.position.y = x
        goal.target_pose.pose.orientation.w = 1.0
        self.client.send_goal(goal)

    def callback_battery(self, msg):
        self.server.send_message_to_all(json.dumps({
            'value': msg.data,
            'type': 'battery',
        }))

    def callback_imu(self, data):
        orientation = data.orientation
        roll, pitch, yaw = euler_from_quaternion([
            orientation.x,
            orientation.y,
            orientation.z,
            orientation.w,
        ])
        self.server.send_message_to_all(json.dumps({
            'value': [degrees(roll), degrees(pitch), degrees(yaw)],
            'type': 'imu',
        }))

    def callback_spp(self, msg):
        self.server.send_message_to_all(json.dumps({
            'lat': self.gps_lat,
            'lng': self.gps_lng,
            'type': 'enu',
        }))

    def callback_rtk(self, msg):
        lat = msg.latitude
        lng = msg.longitude

        self.server.send_message_to_all(json.dumps({
            'lat': lat,
            'lng': lng,
            'type': 'rtk',
        }))

    def spin(self):
        rospy.spin()


if __name__ == "__main__":
    rospy.init_node('viana_ocu')
    controller = Controller()
    controller.spin()
